import type { Metadata } from "next";
import { Calistoga, Lexend } from "next/font/google";
import "./globals.css";

const calistoga = Calistoga({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-calistoga",
	weight: "400",
	preload: true,
});

const lexend = Lexend({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-lexend",
	preload: true,
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${calistoga.variable} ${lexend.variable}`}>
				{children}
			</body>
		</html>
	);
}
